version: '3.1'

services:

  db:
    image: mysql:8.0.28
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'telzir'
      MYSQL_ROOT_PASSWORD: "987412365"
    ports:
      - 3310:3306
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  backend:
    image: backend
    ports:
      - "3050:3050"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: frontend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy